var board_size, makeSourceMap, renderSourceMap;

board_size = 9;

makeSourceMap = function(size) {
  var col, i, j, map, ref, ref1, row;
  map = [];
  for (row = i = 0, ref = size * 3 - 1; 0 <= ref ? i <= ref : i >= ref; row = 0 <= ref ? ++i : --i) {
    row = [];
    for (col = j = 0, ref1 = size * 3 - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; col = 0 <= ref1 ? ++j : --j) {
      row.push(1);
    }
    map.push(row);
  }
  return map;
};

renderSourceMap = function(map) {
  var $map, cell, i, len, results, row;
  $map = $('#map').empty();
  results = [];
  for (i = 0, len = map.length; i < len; i++) {
    row = map[i];
    results.push((function() {
      var j, len1, results1;
      results1 = [];
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        results1.push($map.append($('<div>').addClass("d-" + cell)));
      }
      return results1;
    })());
  }
  return results;
};

(function() {
  return renderSourceMap(makeSourceMap(5));
});{};

// ---
// generated by coffee-script 1.9.2